import type { SacramentMeeting } from "@/lib/types";
const meetings: SacramentMeeting[] = [
{id:1,date:"2026-05-03",meetingType:"testimony",presiding:"Bishop David Chen",conducting:"Brother Elias Grant",announcements:["Ward service project this Saturday","Youth conference registration closes Friday"],openingHymn:{number:19,title:"We Thank Thee, O God, for a Prophet"},openingPrayer:"Sister Nora Williams",wardBusiness:[],stakeBusiness:false,sacramentHymn:{number:169,title:"As Now We Take the Sacrament"},speakers:[{name:"Members of the ward",topic:"Testimonies of Jesus Christ",type:"speaker"}],closingHymn:{number:85,title:"How Firm a Foundation"},closingPrayer:"Brother Owen Price"},
{id:2,date:"2026-08-30",meetingType:"regular",presiding:"Bishop David Chen",conducting:"Sister Maya Hart",announcements:["Sunday School teachers meeting at 1:15 p.m."],openingHymn:{number:2,title:"The Spirit of God"},openingPrayer:"Brother Samuel Lee",wardBusiness:[{description:"Sustain Aaron Blake as ward clerk."}],stakeBusiness:false,sacramentHymn:{number:173,title:"While of These Emblems We Partake"},speakers:[{name:"Sister Ava Morgan",topic:"Finding peace through the Savior",type:"speaker"},{name:"Brother Daniel Brooks",topic:"Choose the right",type:"speaker"}],closingHymn:{number:270,title:"I'll Go Where You Want Me to Go"},closingPrayer:"Sister Ella King"},
{id:3,date:"2026-09-06",meetingType:"testimony",presiding:"Bishop David Chen",conducting:"Brother Elias Grant",announcements:["Fast offering donations are welcome."],openingHymn:{number:98,title:"I Need Thee Every Hour"},openingPrayer:"Sister Lila Reed",wardBusiness:[],stakeBusiness:false,sacramentHymn:{number:171,title:"With Humble Heart"},speakers:[{name:"Members of the ward",topic:"Testimonies of the restored gospel",type:"speaker"}],closingHymn:{number:100,title:"Nearer, My God, to Thee"},closingPrayer:"Brother Isaac Ward"},
{id:4,date:"2026-09-13",meetingType:"regular",presiding:"Bishop David Chen",conducting:"Sister Maya Hart",announcements:["Primary program rehearsal next Sunday."],openingHymn:{number:6,title:"Redeemer of Israel"},openingPrayer:"Brother Noah Kim",wardBusiness:[{description:"Release Sister June Park as Relief Society secretary."}],stakeBusiness:false,sacramentHymn:{number:187,title:"God Loved Us, So He Sent His Son"},speakers:[{name:"Ward Choir",topic:"Abide with Me, 'Tis Eventide",type:"musical-number"},{name:"Sister Clara James",topic:"Ministering with love",type:"speaker"}],closingHymn:{number:220,title:"Lord, I Would Follow Thee"},closingPrayer:"Sister Ruby Cole"},
{id:5,date:"2026-09-20",meetingType:"stake",presiding:"President Marcus Hill",conducting:"Brother Elias Grant",announcements:["Stake conference begins at 10:00 a.m."],openingHymn:{number:27,title:"Praise to the Man"},openingPrayer:"Sister Hannah Young",wardBusiness:[],stakeBusiness:true,sacramentHymn:{number:0,title:"No sacrament hymn"},speakers:[{name:"President Marcus Hill",topic:"Building Zion together",type:"speaker"}],closingHymn:{number:30,title:"Come, Come, Ye Saints"},closingPrayer:"Brother Liam Ross"}
];
export function getMeetings(date?: string): SacramentMeeting[] { return date ? meetings.filter((meeting) => meeting.date === date) : meetings; }
export function getMeetingById(id: number): SacramentMeeting | undefined { return meetings.find((meeting) => meeting.id === id); }
